services:
    backend:
      build: .
      image: ghcr.io/team-vaxxi/int222-backend:dev
      volumes:
        - ./backendImages:/src/images
        - ./.env:/app/.env

networks:
    default:
        external:
            name: int222-network